# Generated by Django 3.2.9 on 2022-04-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0002_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='TheImages',
        ),
    ]
